name: Stale
on:
  schedule:
    # At 10am every day
    - cron: '0 10 * * *'

permissions:
    issues: write
    pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        with:
          days-before-stale: 30
          days-before-close: 7
          remove-stale-when-updated: true
          stale-issue-label: ":ghost: stale"
          stale-issue-message: "This issue has been automatically marked as stale because it appears to have gone quiet. It will be closed in 7 days if no further activity occurs. Thank you
          for your contributions."
          exempt-issue-labels:
            - pinned
            - enhancement
            - help wanted
            - confirmed
            - WIP
          stale-pr-label: ":ghost: stale"
          stale-pr-message: "This pull request has been automatically marked as stale because it appears to have gone quiet. It will be closed in 7 days if no further activity occurs. Thank you
          for your contributions."
          exempt-pr-labels:
            - pinned
            - enhancement
            - WIP
